### PR TITLE
`no-array-for-each`: Ignore `React.Children.forEach`

### LINKED ISSUE #1087: False positive on no-array-for-each
React.Children.forEach is being wrongly flagged.

`no-array-for-each`

```js
React.Children.forEach(children, (child) => {<child />});
```

### PR DESCRIPTION
**Pull request by fisker**
Fixes #1087

### CODE REVIEW

**Comment by sindresorhus** [comment]
I think this rule should share code with https://github.com/sindresorhus/eslint-plugin-unicorn/blob/e54dc6668c818f25dba52b0eee4886ba620075f5/rules/no-array-callback-reference.js#L71-L80

File: test/no-array-for-each.js [hunk 1]
```diff
@@ -5,7 +5,9 @@ test.snapshot({
 	valid: [
 		'new foo.forEach(element => bar())',
 		'forEach(element => bar())',
-		'foo.notForEach(element => bar())'
+		'foo.notForEach(element => bar())',
+		// #1087
+		'React.Children.forEach(children, (child) => {});'
```
Comment (sindresorhus) [inline test/no-array-for-each.js:10]: This could also be `Children.forEach(children, (child) => {});` with named import.

**Comment by fisker** [comment]
I wrote a new function and applied to `no-array-callback-reference` too, the logic changed a little bit, old one ignores `AnyThing.Children`, I don't think it mean to do that. New logic is stricter.

File: rules/no-array-for-each.js [hunk 2]
```diff
@@ -315,6 +316,11 @@ function isFixable(callExpression, sourceCode, {scope, functionInfo, allIdentifi
 	return true;
 }
 
+const ignoredObjects = [
+	'React.Children',
+	'Children'
+];
```
Comment (sindresorhus) [inline rules/no-array-for-each.js:322]: I was thinking we could have a shared utility method that is like `isNotNativeArrayMethod`. In case there are other false-positives in the future.

File: rules/utils/is-node-matches.js [hunk 3]
```diff
@@ -0,0 +1,29 @@
...
+			return false;
+		}
+
+		node = node.object;
+	}
+
+	return true;
+}
+
+function isNodeMatches(node, descriptions) {
```
Comment (sindresorhus) [inline rules/utils/is-node-matches.js:25]: This needs a short doc comment on what `descriptions` is.

File: test/no-array-for-each.js [hunk 4]
```diff
@@ -5,7 +5,10 @@ test.snapshot({
 	valid: [
 		'new foo.forEach(element => bar())',
 		'forEach(element => bar())',
-		'foo.notForEach(element => bar())'
+		'foo.notForEach(element => bar())',
+		// #1087
+		'React.Children.forEach(children, (child) => {});',
+		'React.Children.forEach(children, (child) => {});'
```
Comment (sindresorhus) [inline test/no-array-for-each.js:11]:
```suggestion
		'Children.forEach(children, (child) => {});'
```

File: rules/utils/is-node-matches.js (hunk 3 above)
Comment (sindresorhus) [reply rules/utils/is-node-matches.js:25]: `keyPath` is a commonly used term for `foo.bar` descriptions of a method chain.

File: rules/no-array-callback-reference.js [hunk 5]
```diff
@@ -70,7 +71,7 @@ const iteratorMethods = [
 
 const ignoredCallee = [
 	'Promise',
-	'React.children',
+	'React.Children',
```
Comment (fisker) [inline rules/no-array-callback-reference.js:74]: I think this mean to be `React.Children`.

File: rules/no-array-for-each.js (hunk 2 above)
Comment (fisker) [reply rules/no-array-for-each.js:322]: That's a  good idea, like the [`not-dom-node.js`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/rules/utils/not-dom-node.js), but I was hoping get some help from  [`eslint-utils`](https://github.com/mysticatea/eslint-utils/issues/17), anyway I'll keep this in mind, maybe try in another PR.

**Comment by fisker** [comment]
My 11 month daughter is coding for me... I'm fix after she sleep.

File: rules/no-array-for-each.js (hunk 2 above)
Comment (sindresorhus) [reply rules/no-array-for-each.js:322]: That package isn't very actively maintained. I suggest we just do the utilities here for now and we can move them there later on if it becomes maintained again. Alternatively, you could fork `eslint-utils` for now.
