### PR TITLE
`better-regex`: Fix empty-pattern autofix

### LINKED ISSUE #2314: `better-regex` autofix breaks regular expression syntax: `/|/g` -> `//g`
An empty regular expression such as `//` is invalid and parsed as a line comment instead, which breaks other syntax within the code. I would expect the `better-regex` rule to not propose code with empty regular expressions.

The following is a minimal example:

```js
const expression = /|/;
```

I would expect this expression to be corrected to something like:

```js
const expression = /(?:)/;
```

### PR DESCRIPTION
**Pull request by sindresorhus**
Fixes #2314

A better fix is to fix the library, but I doubt that will happen, so we can work around it for now.

### CODE REVIEW

File: rules/better-regex.js [hunk 1]
```diff
@@ -36,6 +44,7 @@ const create = context => {
 
 		try {
 			optimized = regexpTree.optimize(original, undefined, {blacklist: ignoreList}).toString();
+			optimized = normalizeOptimizedRegexLiteral(optimized);
```
Comment (fisker) [inline rules/better-regex.js:47]: This only fixes `/|/`? 


If so why not 

```
if (original === '/|/') {
  // ...
}
```

?

Comment (sindresorhus) [reply rules/better-regex.js:47]: It is not only `/|/`. I have added a few more test cases.
