### PR TITLE
`prefer-set-has`: Fix string false positives

### LINKED ISSUE #2216: Bug: prefer-set-has false positive for strings in JS
`prefer-set-has` seems to be giving false positives in cases where a string variable has an `.includes()` method called twice:

```js
const text = "abc".slice();
//    ~~~~
// `text` should be a `Set`, and use `text.has()` to check existence or non-existence.

text.includes("a") || text.includes("b");
```

Seen in real world code: [eslint/eslint@`59845bd` (#17515)](https://github.com/eslint/eslint/pull/17515/commits/59845bdb89eaf23ec028b2309fb6ef1dc1d895da#diff-c4eca4aa73ca33a81fc6bfbeb64ebfd27e369dfbeea7e36a73fff08daa46c1b9R252-R253)

### PR DESCRIPTION
**Pull request by sindresorhus**
Fixes #2216

### CODE REVIEW

File: rules/prefer-set-has.js [hunk 1]
```diff
@@ -116,6 +133,7 @@ const create = context => {
 					optionalMember: false,
 				})
 			)
+			&& !isArrayOrStringMethodCallOnStringLikeNode(parent.init)
```
Comment (fisker) [inline rules/prefer-set-has.js]: I don't  like this, we should exclude `slice` and `concate` from  `methodsReturnsArray` and  check them stricter instead.

File: rules/prefer-set-has.js [hunk 2]
```diff
@@ -95,26 +122,7 @@ const create = context => {
...
-					optional: false,
-				})
-				// `Array.from()` and `Array.of()`
-				|| isMethodCall(parent.init, {
-					object: 'Array',
-					methods: ['from', 'of'],
-					optionalCall: false,
-					optionalMember: false,
-				})
-				// Methods that return an array
```
Comment (fisker) [inline rules/prefer-set-has.js:112]: Can we add these comments back?

File: test/prefer-set-has.js [hunk 3]
```diff
@@ -23,6 +23,13 @@ const methodsReturnsArray = [
 	'split',
 ];
 
+const methodsReturnsArrayOrString = [
+	'concat',
+	'slice',
+];
+
+const methodsReturnsOnlyArray = methodsReturnsArray.filter(method => !methodsReturnsArrayOrString.includes(method));
```
Comment (fisker) [inline test/prefer-set-has.js]: This variable should be defined directly. Since the current `methodsReturnsArray` is useless now, it should just remove `concat` and `slice` from `methodsReturnsArray` and use it directly.

I feel like babysitting the AI.. Getting tired

Comment (sindresorhus) [reply test/prefer-set-has.js]: > I feel like babysitting the AI.. Getting tired

I feel this is a bit unfair. I manually review every PR before submitting. I missed this too. Also, it's just minor nitpick. I think you have to do 5x more babysitting for other PRs than the ones I have been doing with AI assistance (not fully AI generated by the way). So in my opinion, this is a net win.

File: rules/prefer-set-has.js [hunk 4]
```diff
@@ -95,26 +126,7 @@ const create = context => {
...
-				|| isMethodCall(parent.init, {
-					methods: methodsReturnsArray,
-					optionalCall: false,
-					optionalMember: false,
-				})
+				isArrayMethodCall(parent.init)
 			)
```
Comment (fisker) [inline rules/prefer-set-has.js]:
```suggestion
			&& isArrayMethodCall(parent.init)
```

Comment (fisker) [reply rules/prefer-set-has.js]: The diff is strange, I mean, should remove `()` around.

File: test/prefer-set-has.js (hunk 3 above)
Comment (fisker) [reply test/prefer-set-has.js]: I don't know, but I feel not interested review some code at all.

For example, this test https://github.com/sindresorhus/eslint-plugin-unicorn/pull/2880/changes#diff-6b5d516c201323584b5cbaa4ec4118b5603a7b401f769c58143d5697312180cbR1.

If was added by a human, I'd review carefully and suggest using an ESLint plugin to run tests, since you don't need to do the `setParent` and `findNode` part.

But as it's generated by AI, I can't say it's wrong, and feel meaningless to tell it run tests in another way.

Comment (sindresorhus) [reply test/prefer-set-has.js]: > If was added by a human, I'd review carefully and suggest using an ESLint plugin to run tests, since you don't need to do the setParent and findNode part.

I don't see how this is any different. I went with the parse stuff as it seemed the simplest to me. AI suggested and **I** agreed. I didn't even think to use ESLint plugin for this. Is this what you had in mind? https://github.com/sindresorhus/eslint-plugin-unicorn/pull/2880/commits/bdfe8401508c9f913685dd79c1f2bc0972841661

File: rules/prefer-set-has.js (hunk 4 above)
Comment (sindresorhus) [reply rules/prefer-set-has.js]: Sorry, I don't get what should be removed.

Comment (fisker) [reply rules/prefer-set-has.js]: L128

Comment (fisker) [reply rules/prefer-set-has.js]:
```diff
-			&& (
-				isArrayMethodCall(parent.init)
-			)
+			&& isArrayMethodCall(parent.init)
```
