### PR TITLE
`prefer-add-event-listener`: Don't autofix non-function assignments

### LINKED ISSUE #2440: `prefer-add-event-listener`: Bad autofix when assignment a non-function object
This is actually in my project, although the code is unreasonable.

```diff
var target

- target.ondrag = true
+ target.addEventListener('drag', true)
```

In addition, if the parameters do not match the types, an exception will be thrown

```js
addEventListener('click', true) 

// Uncaught TypeError: EventTarget.addEventListener: Argument 2 is not an object.
```

### PR DESCRIPTION
**Pull request by sindresorhus**
Fixes #2440

### CODE REVIEW

File: rules/prefer-add-event-listener.js [hunk 1]
```diff
@@ -49,6 +49,19 @@ const shouldFixBeforeUnload = (assignedExpression, nodeReturnsSomething) => {
 
 const isClearing = node => isUndefined(node) || isNullLiteral(node);
 
+const notFunctionNodeTypes = new Set([
```
Comment (fisker) [inline rules/prefer-add-event-listener.js]: Reuse   `isNodeValueNotFunction`?

Comment (sindresorhus) [reply rules/prefer-add-event-listener.js]: Done
