### PR TITLE
`consistent-destructuring`: Fix false positive after reassignment

### LINKED ISSUE #1407: consistent-destructuring: incorrect report if the value is reassigned
```js
const { children } = parent
parent.children = combine(children)
for(const child of parent.children) { // incorrect report here
}
```

### PR DESCRIPTION
**Pull request by sindresorhus**
Fixes #1407

### CODE REVIEW

File: rules/consistent-destructuring.js [hunk 1]
```diff
@@ -33,6 +34,36 @@ const isChildInParentScope = (child, parent) => {
...
 
+const getRootIdentifier = expression => {
+	while (expression?.type === 'MemberExpression') {
+		expression = expression.object;
+	}
+
+	return expression?.type === 'Identifier' ? expression : undefined;
+};
+
+const isRootVariableReassigned = (declaration, memberExpressionNode, memberScope, sourceCode) => {
```
Comment (fisker) [inline rules/consistent-destructuring.js:45]: I don't think this is correct, the reassign code can be anywhere that have access to the variable.

For example,

```
let foo = bar;

const {a} = foo;

reassign();

console.log(foo.a);

function reassign(){
  foo = baz;
}
```

Anyway, I don't have a good solution either.

Comment (sindresorhus) [reply rules/consistent-destructuring.js:45]: I have adjusted reassignment checks to avoid unsafe stuff while still reporting reads before same-scope reassignments. I think that's the best we can do.
