### PR TITLE
`prevent-abbreviations`: Ignore `i18n` and `l10n`

### LINKED ISSUE #1188: prevent-abbrevations and i18n
When using `i18n` as a file or variable name, `unicorn/prevent-abbreviations` will report a problem seemingly because of the `i`:

> The variable `i18n` should be named `index18n`. A more descriptive name will do too.

This is also not easily fixed by overriding replacements since the rule seems to catch on the `i`, so using `i18n:` does not work. Instead, you have to have this replacement: `{ i: { index: false } }`.

I think that `i18n` is well-known and popular enough that it doesn't merit triggering this rule.

### PR DESCRIPTION
**Pull request by Divlo**
Hey :wave:,

This PR fixes #1188
It ignores the `i18n` keyword for the `prevent-abbreviations` rule, as it is well-known and popular enough.

I also like the idea of, explicit > implicit, but sometimes, things are done like that, so we can relax a bit the rule.

### CODE REVIEW

File: rules/prevent-abbreviations.js [hunk 1]
```diff
@@ -96,6 +96,10 @@ const getNameReplacements = (name, options, limit = 3) => {
 		return {total: 0};
 	}
 
+	if (name.includes('i18n')) {
```
Comment (sindresorhus) [inline rules/prevent-abbreviations.js:99]: It should not be hard-coded directly here. There should be a list like `allowList` that is checked in the above if-statement.

**Comment by fisker** [comment]
Let's ignore `l10n` too?

File: rules/prevent-abbreviations.js (hunk 1 above)
Comment (Divlo) [reply rules/prevent-abbreviations.js]: Done!
I added `i18n` and `l10n` to `defaultAllowList`.

But we should probably move it to `defaultReplacements`, because something like `const i18nData = {}` will not work, and it will still suggests to refactor it to `index18nData` but that's wrong.

What do you think ? :smile:

Comment (fisker) [reply rules/prevent-abbreviations.js]: It's known https://github.com/sindresorhus/eslint-plugin-unicorn/issues/752, you'll have to use `ignore` option for now.

Comment (Divlo) [reply rules/prevent-abbreviations.js]: Right, so I added `defaultIgnore`, should we also, add a new option, `extendDefaultIgnore` ?

Comment (sindresorhus) [reply rules/prevent-abbreviations.js]: > Right, so I added defaultIgnore, should we also, add a new option, extendDefaultIgnore ?

Nah. We can add it when it's needed. I see no reason to not want these ignores.

**Review by sindresorhus — APPROVED** [review]

**Review by fisker — APPROVED** [review]
