### PR TITLE
Handle lack of package.json in `expiring-todo-comments` rule

### LINKED ISSUE #394: `expiring-todo-comments` doesn't work when linting stand-alone files
Related to #373. Ping @lubien.

I'm using the latest version of `eslint-plugin-unicorn`, and `eslint v5`.

I'm using the latest version of the VS Code editor, and the latest version of the [vscode-eslint](https://github.com/microsoft/vscode-eslint) extension.

The extension allows to lint untitled files (after changing the untitled file's lang to JavaScript), and files that don't belong to a JS project with package.json. But an error is thrown with this rule, since it checks for a `package.json`, and an untitled file isn't even a file at all, and therefore also has no relevant `package.json`. And stand-alone files don't have package.json.

Error, whenever I open an untitled or stand-alone file in VSC:

```
[Info  - 4:23:17 PM] ESLint server stopped.
[Info  - 4:23:18 PM] ESLint server running in node v10.11.0
[Info  - 4:23:18 PM] ESLint server is running.
[Info  - 4:23:19 PM] ESLint library loaded from: /usr/local/lib/node_modules/eslint/lib/api.js
[Error - 4:23:21 PM] ESLint stack trace:
[Error - 4:23:21 PM] TypeError: Cannot read property 'package' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/eslint-plugin-unicorn/rules/expiring-todo-comments.js:20:29)
    at Object.<anonymous> (/usr/local/lib/node_modules/eslint-plugin-unicorn/rules/expiring-todo-comments.js:499:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at module.exports (/usr/local/lib/node_modules/eslint-plugin-unicorn/node_modules/import-modules/index.js:41:21)
```

### PR DESCRIPTION
**Pull request by lubien**
@garyking came with this scenario of a packageless project. For this my choice would be not to allow package related triggers to work at least until a proper package.json file is set up.

Even tho the original issue says eslint 5, this happens also in version 6.

Fixes #394

### CODE REVIEW

File: rules/expiring-todo-comments.js [hunk 1]
```diff
@@ -17,7 +17,8 @@ const MESSAGE_ID_ENGINE_MATCHES = 'engineMatches';
 const MESSAGE_ID_REMOVE_WHITESPACES = 'removeWhitespaces';
 const MESSAGE_ID_MISSING_AT_SYMBOL = 'missingAtSymbol';
 
-const pkg = readPkgUp.sync().package;
+const hasPackage = readPkgUp.sync();
+const pkg = hasPackage ? hasPackage.package : {};
```
Comment (fisker) [inline rules/expiring-todo-comments.js]: This two line seems weird.

Comment (fisker) [reply rules/expiring-todo-comments.js]: first thinking

```js
const {package: pkg = {}} = readPkgUp.sync() || {};
const hasPackage = ??? // can't detect
```

next might better, but extra line

```js
const result= readPkgUp.sync();
const hasPackage = Boolean(result)
const pkg = hasPackage ? result.package : {};
````

or maybe this one

```js
const {
  package: pkg = {}, 
  hasPackage = true
} = readPkgUp.sync() || {hasPackage: false}
```

@lubien what do you think

File: rules/expiring-todo-comments.js [hunk 2]
```diff
@@ -173,11 +174,7 @@ function semverComparisonForOperator(operator) {
 
 const create = context => {
 	const options = {
-		terms: [
-			'todo',
-			'fixme',
-			'xxx'
-		],
+		terms: ['todo', 'fixme', 'xxx'],
```
Comment (sindresorhus) [inline rules/expiring-todo-comments.js]: In the future, don't do unrelated changes.

File: rules/expiring-todo-comments.js (hunk 1 above)
Comment (sindresorhus) [reply rules/expiring-todo-comments.js]: I agree. I just needed to get this out.

Should probably have been:

```js
const packageResult = readPkgUp.sync();
const hasPackage = Boolean(packageResult);
const packageJson = hasPackage ? packageResult.package : {};
```

Comment (fisker) [reply rules/expiring-todo-comments.js]: Did we comment at the same time? LOL
what do you think my last code

Comment (sindresorhus) [reply rules/expiring-todo-comments.js]: Hehe. Seems so. I didn't see your comment until now. Let's go with mine, which is your second one, just with more verbose naming.

Comment (fisker) [reply rules/expiring-todo-comments.js]: /cc @lubien Could you please send another PR to apply this?

File: rules/expiring-todo-comments.js (hunk 2 above)
Comment (lubien) [reply rules/expiring-todo-comments.js]: Oh. Might have been the linter but might bad for leaving it, sorry. Won't happen again.

File: rules/expiring-todo-comments.js (hunk 1 above)
Comment (lubien) [reply rules/expiring-todo-comments.js]: Sure! But I need a few hours before I can do this if it's not an issue.

Comment (lubien) [reply rules/expiring-todo-comments.js]: https://github.com/sindresorhus/eslint-plugin-unicorn/pull/399
