### PR TITLE
`consistent-function-scoping`: Ignore anything containing JSX

### LINKED ISSUE #376: consistent-function-scoping breaks down on React HOCs
Given this code:

```js
function withSomething() {
  return function withSomethingFactory(WrappedComponent) {
    function WithSomething(props) {
      // HOC does something cool
      return <WrappedComponent {...props} />;
    }

    return WithSomething;
  };
}
```

The rule fails on line 3. However, `WrappedComponent` is being referenced from the parent as a JSX element.

### PR DESCRIPTION
**Pull request by MrHen**
Fixes #376.
Depends on #378.

I could not find a quick way to include JSX elements in the reference detection. It looks like the scope utilities don't recognize JSX.

We can circle back around to this later but I wanted to get the bugs cleared out first.

### CODE REVIEW

File: rules/consistent-function-scoping.js [hunk 1]
```diff
@@ -121,30 +121,48 @@ const create = context => {
...
+			} else {
+				reports.push({
+					node,
+					messageId: MESSAGE_ID_FUNCTION
+				});
+			}
+		},
+		JSXElement: () => {
+			// Turn off this rule if we see a JSX element because scope
+			// references does not include JSXElement nodes.
```
Comment (MrHen) [inline rules/consistent-function-scoping.js]: Copying [comment](https://github.com/MrHen/eslint-plugin-unicorn/pull/1#discussion_r325481128) from @sindresorhus:

> Can you open an ESLint issue about this afterwards?

Looks like there was a similar issue opened here: https://github.com/eslint/eslint/issues/3622

I can try getting something like that hooked up. Ideally, if someone who uses `eslint-plugin-unicorn` also had `eslint-plugin-react` then it would "just work". I'm not sure if we can realistically test for that, though.
