### PR TITLE
`prefer-top-level-await`: Fix false positive with `Promise.all`

### LINKED ISSUE #2177: False positive in `prefer-top-level-await`
Should not report on following cases.

```js
async function getStat() {}

const [core, pure, bundle] = await Promise.all([
  getStat('core-js'),
  ALL && getStat('core-js-pure'),
  ALL && getStat('core-js-bundle'),
]);
```

https://github.com/zloirock/core-js/blob/ab5f0252fcbfb58aebd636d7c3b6585b2f4cc320/scripts/downloads-by-versions.mjs#L18-L24

### PR DESCRIPTION
**Pull request by sindresorhus**
Fixes #2177

### CODE REVIEW

File: rules/prefer-top-level-await.js [hunk 1]
```diff
@@ -47,16 +48,45 @@ const isAwaitExpressionArgument = node => {
 	return node.parent.type === 'AwaitExpression' && node.parent.argument === node;
 };
 
+const isArrayElementWrapper = node => (
+	(node.parent.type === 'ChainExpression' && node.parent.expression === node)
```
Comment (fisker) [inline rules/prefer-top-level-await.js:52]: This not tested.

File: rules/prefer-top-level-await.js [hunk 2]
```diff
@@ -47,16 +48,45 @@ const isAwaitExpressionArgument = node => {
...
+
 // `Promise.{all,allSettled,any,race}([foo()])`
-const isInPromiseMethods = node =>
-	node.parent.type === 'ArrayExpression'
-	&& node.parent.elements.includes(node)
-	&& isMethodCall(node.parent.parent, {
+const isInPromiseMethods = node => {
+	let expression = node;
+	while (
+		expression.parent
```
Comment (fisker) [inline rules/prefer-top-level-await.js]: `expression.parent` check should be removed. I don't think it's possible to be nullish.

File: rules/prefer-top-level-await.js [hunk 3]
```diff
@@ -47,16 +48,42 @@ const isAwaitExpressionArgument = node => {
...
+	|| (
+		isLogicalExpression(node.parent)
+		&& (
+			node.parent.right === node
+			|| (
+				node.parent.left === node
+				&& node.parent.operator !== '&&'
+			)
+		)
+	)
```
Comment (fisker) [inline rules/prefer-top-level-await.js:69]: Ternary is also common, maybe we can also check it.

**Review by fisker — APPROVED** [review]
