### PR TITLE
`prefer-starts-ends-with`: Add auto-fix

### LINKED ISSUE #625: prefer-starts-ends-with: Add autofix
It'd be very useful if [`prefer-starts-ends-with`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/prefer-starts-ends-with.md) would have a autofix available.

### PR DESCRIPTION
**Pull request by fisker**
This PR contains code from https://github.com/sindresorhus/eslint-plugin-unicorn/pull/710

Fixes #625

### CODE REVIEW

File: test/prefer-starts-ends-with.js [hunk 1]
```diff
@@ -58,17 +47,93 @@ ruleTester.run('prefer-starts-ends-with', rule, {
...
+		}),
+		// Parenthesized
+		{
+			code: '/^b/.test(("a"))',
+			output: '("a").startsWith((\'b\'))',
+			errors: [{messageId: MESSAGE_STARTS_WITH}]
+		},
+		{
+			code: '(/^b/).test(("a"))',
+			output: '("a").startsWith((\'b\'))',
```
Comment (fisker) [inline test/prefer-starts-ends-with.js:83]: string  `'b'` is  parenthesized because the  original `("a")` left the `()` when  replacing text, I'm not  going  to remove them.

**Comment by sindresorhus** [comment]
Can you fix the merge conflict?
