### PR TITLE
`filename-case`: Ignore `$` in filenames

### LINKED ISSUE #1627: $file-name.tsx fails the kebab-case rule (filename-case)
I have a file `$file-name.tsx` and `filename-case` rule turned on.

I have an error saying: Filename is not in kebab case. Rename it to `file-name.tsx`

### PR DESCRIPTION
**Pull request by matmilbury**
Fixes #1627 

There is no test case that demonstrates why `$` should not be ignored.

### CODE REVIEW

File: test/filename-case.mjs [hunk 1]
```diff
@@ -79,6 +79,7 @@ test({
 		testCase('src/foo/___foo-bar.js', 'kebabCase'),
 		testCase('src/foo/_FooBar.js', 'pascalCase'),
 		testCase('src/foo/___FooBar.js', 'pascalCase'),
+		testCase("src/foo/$foo.js"),
```
Comment (fisker) [inline test/filename-case.mjs:82]: Can you also add an invalid case with filename contains `$`?

Comment (matmilbury) [reply test/filename-case.mjs:82]: `$` in the filename will never cause the filename to be invalid because this character has nothing to do with casing.

**Review by sindresorhus — APPROVED** [review]

File: test/filename-case.mjs (hunk 1 above)
Comment (fisker) [reply test/filename-case.mjs]: https://github.com/sindresorhus/eslint-plugin-unicorn/pull/1628/commits/67737fd0bdcae1457e6572dce38fb6e57fb27dc1?
