### PR TITLE
Fix `prefer-includes` fixer omitting parentheses

### LINKED ISSUE #278: Auto-fix for prefer-includes removes too many/wrong parenthesis
Input:

```javascript
const forceLatest = ((url.parse(req.url).query || '').indexOf('latest') !== -1);
```
```javascript
return (req.originalUrl || '').indexOf(page.path) !== -1;
```

Expected output:

```javascript
const forceLatest = (url.parse(req.url).query || '').includes('latest');
```
```javascript
return (req.originalUrl || '').includes(page.path);
```

Output from auto-fixer:

```javascript
const forceLatest = (url.parse(req.url).query || ''.includes('latest'));
```
```javascript
return req.originalUrl || ''.includes(page.path);
```

### PR DESCRIPTION
**Pull request by golopot**
fixes #278

Since the `memberExpressionNode.object` does not includes the parens, I work around by accessing the text before "dot".

### CODE REVIEW

File: rules/prefer-includes.js [hunk 1]
```diff
@@ -12,13 +12,12 @@ const isIndexOf = node => {
...
-	context.getSourceCode().getText(node)
-);
-
 const report = (context, node, target, pattern) => {
-	const targetSource = getSourceCode(context, target);
-	const patternSource = getSourceCode(context, pattern);
+	const sourceCode = context.getSourceCode();
+	const memberExpressionNode = target.parent;
+	const dotToken = sourceCode.getTokenBefore(memberExpressionNode.property);
+	const targetSource = sourceCode.getText().slice(memberExpressionNode.start, dotToken.start);
```
Comment (alexzherdev) [inline rules/prefer-includes.js]: As found in #272, `start` is not compatible with TS parser
```suggestion
	const targetSource = sourceCode.getText().slice(memberExpressionNode.range[0], dotToken.range[0]);
```

**Comment by sindresorhus** [comment]
Thanks for fixing :)
