### PR TITLE
Detect unnecessary `Promise.resolve`/`reject` in promise callback functions

### LINKED ISSUE #1609: Rule proposal: No unnecessary `Promise.resolve/reject()` in async functions
### Description

The rule should prevent using moot `Promise.reject` and `Promise.resovle` calls in async functions.

Rule name suggestion: `no-useless-promise-resolve-reject`

### Fail

```js
const main = async foo => {
	if (foo > 4) {
		return Promise.reject(new Error('🤪'));
	}

	return Promise.resolve(result);
};
```

### Pass

```js
const main = async foo => {
	if (foo > 4) {
		throw new Error('🤪');
	}

	return result;
};
```

### PR DESCRIPTION
**Pull request by cherryblossom000**
Implements https://github.com/sindresorhus/eslint-plugin-unicorn/issues/1609#issuecomment-970571215

Fixes  #1609

### CODE REVIEW

File: rules/no-useless-promise-resolve-reject.js [hunk 1]
```diff
@@ -40,9 +40,26 @@ function getFunctionNode(node) {
...
+		&& node.parent.type === 'CallExpression'
+		&& node.parent.callee.type === 'MemberExpression'
+		&& node.parent.callee.property.type === 'Identifier'
+	) {
+		const {callee: {property}, arguments: arguments_} = node.parent;
+		if (property.name === 'then') {
+			isInPromiseThenOrCatchCallback = arguments_[0] === node || arguments_[1] === node;
+		} else if (property.name === 'catch') {
+			isInPromiseThenOrCatchCallback = arguments_[0] === node;
+		}
```
Comment (fisker) [inline rules/no-useless-promise-resolve-reject.js:56]: `Promise#finally()` should also checked as welll.

File: rules/no-useless-promise-resolve-reject.js [hunk 2]
```diff
@@ -141,14 +157,15 @@ const create = context => {
 
 	return {
 		[selector](callExpression) {
-			const {functionNode, isInTryStatement} = getFunctionNode(callExpression);
-			if (!functionNode || !functionNode.async) {
+			const isReject = callExpression.callee.property.name === 'reject';
+			const {functionNode, isInTryStatement, isInPromiseThenOrCatchCallback} = getFunctionNode(callExpression);
+			if (!functionNode || (!functionNode.async && (!isInPromiseThenOrCatchCallback || isReject))) {
```
Comment (fisker) [inline rules/no-useless-promise-resolve-reject.js:162]: I don't understand this part, why we should care if it's reject here?

File: rules/no-useless-promise-resolve-reject.js [hunk 3]
```diff
@@ -40,9 +40,26 @@ function getFunctionNode(node) {
 		}
 	}
 
+	let isInPromiseThenOrCatchCallback = false;
```
Comment (fisker) [inline rules/no-useless-promise-resolve-reject.js:43]: The logic is the function is async or it's promise callback, we run check.

File: rules/no-useless-promise-resolve-reject.js (hunk 2 above)
Comment (cherryblossom000) [reply rules/no-useless-promise-resolve-reject.js:162]: My bad, for some reason I thought `promise.catch(() => Promise.reject(error))` would be behave differently to `promise.catch(() => { throw error })`.

File: rules/no-useless-promise-resolve-reject.js [hunk 4]
```diff
@@ -142,7 +142,27 @@ const create = context => {
...
+			if (!functionNode) {
+				return;
+			}
+
+			let isInPromiseThenOrCatchCallback = false;
+			if (
+				functionNode.parent
+				&& functionNode.parent.type === 'CallExpression'
+				&& functionNode.parent.callee.type === 'MemberExpression'
+				&& functionNode.parent.callee.property.type === 'Identifier'
```
Comment (fisker) [inline rules/no-useless-promise-resolve-reject.js:155]: `&& !functionNode.parent.callee.computed`

File: rules/no-useless-promise-resolve-reject.js [hunk 5]
```diff
@@ -142,7 +142,27 @@ const create = context => {
...
+			) {
+				const {callee: {property}, arguments: arguments_} = functionNode.parent;
+				if (property.name === 'then') {
+					isInPromiseThenOrCatchCallback = arguments_[0] === functionNode || arguments_[1] === functionNode;
+				} else if (property.name === 'catch' || property.name === 'finally') {
+					isInPromiseThenOrCatchCallback = arguments_[0] === functionNode;
+				}
+			}
```
Comment (fisker) [inline rules/no-useless-promise-resolve-reject.js:163]: Can you extract this to a function? maybe `isPromiseCallback(functionNode)`

Comment (fisker) [reply rules/no-useless-promise-resolve-reject.js:163]: So we can `if (!functionNode || (!functionNode.async && !isPromiseCallback(functionNode)))`

**Review by fisker — APPROVED** [review]

**Comment by fisker** [comment]
@cherryblossom000 We may want to mention promise callback functions in the description and the rule docs.

**Comment by cherryblossom000** [comment]
Would returning a value from the `Promise#finally` callback do anything (if the value isn't a rejected promise)?

```js
> await Promise.resolve(1).finally(() => 2)
1
> await Promise.reject(1).finally(() => 2)
Uncaught 1
```

**Comment by fisker** [comment]
> Would returning a value from the Promise#finally callback do anything

I think it's ignored, but we are not breaking things(I think).

**Comment by sindresorhus** [comment]
Linting is failing

File: rules/no-useless-promise-resolve-reject.js [hunk 6]
```diff
@@ -46,6 +46,26 @@ function getFunctionNode(node) {
...
+		&& !node.parent.callee.computed
+		&& node.parent.callee.property.type === 'Identifier'
+	) {
+		const {callee: {property}, arguments: arguments_} = node.parent;
+		if (property.name === 'then') {
+			return arguments_[0] === node || (arguments_[0].type !== 'SpreadElement' && arguments_[1] === node);
+		}
+
+		if (property.name === 'catch' || property.name === 'finally') {
+			return arguments_[0] === node;
```
Comment (j-f1) [inline rules/no-useless-promise-resolve-reject.js:62]: I don’t know how common non-Promise then/catch/finally methods are in real code. Do you think it would make sense to do a length/type check on the arguments list to confirm it’s likely to be a valid Promise call?

Comment (fisker) [reply rules/no-useless-promise-resolve-reject.js]: https://github.com/sindresorhus/eslint-plugin-unicorn/pull/1666/commits/21c2773c6e187c9445bac9d7e2c14826119d022d
